FROM python:3.11-slim
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
# Change the last part from 'app:app' to 'bigdatahere:app'
CMD ["gunicorn", "-b", "0.0.0.0:8080", "bigdatahere:app"]